# Generated by Django 2.2 on 2022-01-20 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.CreateModel(
            name='Datatable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_1', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_2', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_3', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_4', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_5', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_6', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_7', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_8', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_9', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_10', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_11', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_12', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_13', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_14', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_15', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_16', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_17', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_18', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_19', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_20', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_21', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_22', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_23', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_24', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_25', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_26', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_27', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_28', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_29', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_30', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_31', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_32', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_33', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_34', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_35', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_36', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_37', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_38', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_39', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_40', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_41', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_42', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_43', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_44', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_45', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_46', models.DateField(blank=True, null=True)),
                ('cell_47', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
